### ISSUE TITLE
如果密钥第一位为0时，则天蝎工具计算的密钥有误

### ISSUE THREAD

**Issue by Epicccal** [shack2/skyscorpion#2]
版本是20210322
在测试时我使用了 test 作为密钥，该密钥的 md5sum 为 098f6bcd4621d373cade4e832627b4f6
当我使用天蝎工具连接webshell时，发现始终连接失败。
通过对 /org/shack2/service/BaseService.checkStatus() 下断点后，发现工具计算的密钥有误
<img width="1426" alt="tianxiebug" src="https://user-images.githubusercontent.com/34046030/145514368-07a14440-e51c-493b-86e3-7c5506ead90d.png">
搜了一下原因，原因应该是 BigInteger 转换的问题，当被转换的 MD5 首位为 0 时，会删除这个 0 ，从而导致密钥获取错误。可以参考这个帖子 : https://blog.51cto.com/maweil/1913478 
师傅可以针对这个点做一下改进。

**Comment by shack2** [comment]
感谢，稍后修复。

**Comment by shack2** [comment]
已经修复
